### ISSUE TITLE
Migrate l10n modules from community-data-files

### ISSUE THREAD

**Issue by clonedagain** [OCA/l10n-france#1]
The project https://github.com/OCA/community-data-files currently contains 2 modules that are localization-related, so it has been suggested they should be moved to other existing l10n_\* projects.

**Comment by clonedagain** [comment]
l10n_fr_naf_ape could go to https://github.com/OCA/l10n-france. Should I make PRs to this aim in v7, or wait until it is ported to v8?

l10n_eu_nace is a localization for the whole European Union, not one country. What would be the right place for this ?

**Comment by alexis-via** [comment]
l10n-france welcomes all the France-specific modules, so it would welcome l10n_fr_naf_ape. The modules of l10n-france are still on Launchpad for the moment (https://code.launchpad.net/openerp-french-localization), but they should move it soon i.e. as soon as someone with the required git skills has the time to do it.

Other OCA modules such as l10n_fr_siret and account_banking_fr_lcr may also be moved here.

**Comment by clonedagain** [comment]
Thank for your reply.  What about l10n_eu_nace?

**Comment by yvaucher** [comment]
@clonedagain We still have no home for `l10n_eu_nace`?

What about a new repo l10n_europe or l10n_european_union?

**Comment by clonedagain** [comment]
@yvaucher whatever the project managers prefer! 
Maybe even in a more generic repo "l10n-others" ?

`l10n_eu_nace` currently lives in `community-data-files`, it can remain there or I can easily move it elsewhere when it's decided.

By the way, `community-data-files` now contains _only_ `l10n_eu_nace` and never really gained traction because no-one found a use for it apart from localization.
So maybe you would simply want to rename the whole repo ?
