### ISSUE TITLE
INSEE number

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-france#166]
Hello,

One of our customer wants to have the "INSEE number" on the partner form.

Is there any recommendation of the l10n-france community about that? A first search did not reveal a module doing that.

**Comment by remi-filament** [comment]
Hello @sbidoul,
do you mean for people, territories or for companies ?
For companies, this would be SIREN/SIRET pair, for which we have created a module to retrieve these automatically from INSEE public API (see #163 )
For people, this would "numéro de sécurité sociale", I do not think you can retrieve it from any public database (for obvious privacy reasons), but you could probably create a method to check that it has the correct format ?
For territories, you can download codes [here](https://www.insee.fr/fr/information/2115000) and you may want to create a corresponding module to add these data in Odoo ?

**Comment by alexis-via** [comment]
I guess he was talking about the SIRET number, which is attributed by INSEE. So l10n_fr_siret will do the job.

**Comment by cvinh** [comment]
Hello
I have same question for individuals, then we talk about the INSEE number (NIR)
Thanks
