### ISSUE TITLE
FEC back in OCA

### ISSUE THREAD

**Issue by alexis-via** [OCA/l10n-france#197]
The goal of this issue is to expose my idea about FEC before I start doing the dev work in OCA. I would like to improve the FEC module l10n_fr_fec on v12 (and probably v10 too):
- add option to choose the encoding (UTF-8, latin1, ...) and maybe also add an option to replace accentuated characters by non-accentuated equivalents
- maybe add other options about the CSV structure (field separator, ...)
- add option to remove the information of the partner on expense, VAT and revenue accounts (only keep it on reconciled accounts)
- replace the .csv extension by a .txt extension

I won't propose a PR on odoo, because it won't be accepted (many PRs are just ignored ; it is impossible to add fields on a stable version).

So my idea would be to maintain a FEC module in OCA. For that, we would take the current l10n_fr_fec as basis and rename it to l10n_fr_fec_oca (or any better name that the community would suggest).
The module l10n_fr_fec  from the official addons depends on 'l10n_fr' and 'account' and is auto_install = True.
I have 2 possible solutions in mind :
1) l10n_fr_fec_oca depends on l10n_fr_fec and inherits the menu entry to replace it
2) l10n_fr_fec_oca only depends on 'account' and 'l10n_fr' (and 'date_range'). Users would need to uninstall the l10n_fr_fec manually to avoid the double "FEC" menu entry.

**Comment by alexis-via** [comment]
Here is my PR https://github.com/OCA/l10n-france/pull/202

**Comment by Maurice67205** [comment]
Hi Alexis
the l10n_fr_fec module enables to export a FEC file from an Odoo Accounting database
Is there a module to import a FEC file ? I found a link to smile_account_fec_import but it is only for V8

https://apps.odoo.com/apps/modules/8.0/smile_account_fec_import/

Regards

Maurice

**Comment by alexis-via** [comment]
To import a FEC, there is also my module account_move_csv_import, cf https://github.com/akretion/account-move-import/blob/12.0/account_move_csv_import/wizard/import_move.py#L36

**Comment by Maurice67205** [comment]
Hello Alexis
I tested it with the FEC export from another instance ; worked well
I will test it with a FEC Export from another software.
It needs the installation of several other modules, so it cannot be used on an Odoo online instance.
Regards
Maurice

**Comment by alexis-via** [comment]
@Maurice67205 If you want to take advantage of OCA modules, you should certainly move away from Odoo Online.

**Comment by Maurice67205** [comment]
@alexis-via Fully agree with you I must convince the customer now

**Comment by pasgou** [comment]
If you want to have a "legally good enough" FEC, you should 
- make "description" field necessary and not optionnal (cause else the move line label is null or "/" wich is not accepted by french administration). It should be place elsewhere to be seen by user.
- or compute the move line label with some others fields if description is null.

**Comment by alexis-via** [comment]
@pasgou I guess you are talking about the "name" field on account.move.line... are you ?

**Comment by pasgou** [comment]
> @pasgou I guess you are talking about the "name" field on account.move.line... are you ?

I can say that that is the field which is completed by the "reference/description" in the sale order.

**Comment by pasgou** [comment]
> > @pasgou I guess you are talking about the "name" field on account.move.line... are you ?
> 
> I can say that that is the field which is completed by the "reference/description" in the sale order.

To be complete 
In account.invoice,

def action_move_create(self):
	name = line.name or ''

Why not "or invoice number" or something else which is explicite?

In the fec module the sql command write "/" if there is nothing wroten but perhaps it could be useful to re_write the method to write an explicite and informative label.
If I understand well it wroten like this :
```

CASE WHEN aml.name IS NULL OR aml.name = '' THEN '/'
                WHEN aml.name SIMILAR TO '[\t|\s|\n]*' THEN '/'
                ELSE replace(replace(replace(replace(
                aml.name, '|', '/'), '\t', ''), '\n', ''), '\r', '')
            END AS EcritureLib,

```
I don't understand well all the sequence with replace, so you could explain to me, it could be cool...

If you test a fec file with the tool delivered by EFL it's one of the "errors", but the easiest to correct.
