### ISSUE TITLE
Chorus Pro migration to v12

### ISSUE THREAD

**Issue by flotho** [OCA/l10n-france#218]
Hi @alexis-via ,

I would like to have your point of view regarding a migration of chorus pro to v12?
could you help us on this and show us the road ?

Regards

**Comment by alexis-via** [comment]
The target is not just a simple migration to v12, but the support of PISTE https://developer.aife.economie.gouv.fr/

**Comment by saxomanu** [comment]
Hi @alexis-via 
I'm interessting into this work too, in v13.
How can i help you ?

Regards

**Comment by rpinset** [comment]
Hello,
I understand @alexis-via  that this is PISTE support but is this module on the OCA roadmap for migration to v12 and v13?
Unless there is an alternative that I haven't found?
cordially

**Comment by alexis-via** [comment]
Chorus Pro/PISTE for v12 is here: https://github.com/OCA/l10n-france/pull/229
Chorus Pro/PISTE for v13 is here : https://github.com/OCA/l10n-france/pull/237
Read the comments to know the PRs on which it depends.

**Comment by alexis-via** [comment]
And v12 PR is now merged in OCA/l10n-france !
