### ISSUE TITLE
[13.0] [Install. BUG] "l10n_fr_account_tax_unece" Getting Bug during module installation

### ISSUE THREAD

**Issue by NCS-75** [OCA/l10n-france#241]
Context :
OCB 13.0 Odoo Server up to date [(07/11/2020),] on Virgin database , to reproduce issue faced on my test environnement.
Get bug, also on runbot : http://3430748-13-0-06e23c.runbot2.odoo-community.org/

Steps to reproduce :
Check module dependancy,  (account_tax_unece & l10n_fr ). Considering that "auto_installable": True, have not effect on this module, then,
Try to Install the module : "l10n_fr_account_tax_unece" module
So, now, you see bug tracking message.

Odoo Server Error :
```
Traceback (most recent call last):
  File "/opt/odoo/odoo_v13/server/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/odoo/odoo_v13/server/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/odoo/odoo_v13/server/odoo/tools/convert.py", line 527, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
  Exception: Cannot update missing record 'l10n_fr.tva_acq_intra_normale'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
.../...
File "/opt/odoo/odoo_v13/server/odoo/tools/convert.py", line 527, in _tag_record
    raise Exception("Cannot update missing record %r" % xid)
odoo.tools.convert.ParseError: "Cannot update missing record 'l10n_fr.tva_acq_intra_normale'" while parsing /opt/odoo/odoo_v13/oca_addons/l10n_fr_account_tax_unece/data/account_tax_template.xml:7, near
<odoo>
    <!-- 20.0 -->
    <record id="l10n_fr.tva_normale" model="account.tax.template">
        <field name="unece_type_id" ref="account_tax_unece.tax_type_vat"/>
        <field name="unece_categ_id" ref="account_tax_unece.tax_categ_s"/>
        <field name="unece_due_date_id" ref="account_tax_unece.date_5"/>
    </record>
    <!-- 20.0-TTC -->
```
@alexis-via Thanks in advance for your help.
.
![1-Issue-l10n_fr_account_tax_unece](https://user-images.githubusercontent.com/59052920/87249469-92ad7580-c45f-11ea-81d4-c133df4d2106.JPG)
![2-Issue-l10n_fr_account_tax_unece](https://user-images.githubusercontent.com/59052920/87249475-980ac000-c45f-11ea-947a-31f755be52c3.JPG)

**Comment by alexis-via** [comment]
This crash is linked to a recent change in l10n_fr in v13, in this commit : https://github.com/odoo/odoo/commit/a5ddba34cc336e380f98c36ac4737ab97043eb76#diff-a1e58b93e4fc31063f8bdd7b38d97343
My database has been generated before this commit, that's why I didn't see the bug.
We need to fix it.
