### ISSUE TITLE
French Letter of Change V13 does not create a payment

### ISSUE THREAD

**Issue by Maurice67205** [OCA/l10n-france#263]
Using the V13 module account_banking_fr_lcr I can generate an LCR txt file to be sent to the bank and that will set the corresponding invoices to PAID but when I register the bank statement I cannot reconcile it with the payment because it is not there
I'm using this module in an OE 13 context

Maurice

**Comment by Maurice67205** [comment]
Payment is also not created in V14

**Comment by alexis-via** [comment]
This PR solves the pb: https://github.com/OCA/account-reconcile/pull/382
This was also discussed here https://github.com/OCA/bank-payment/issues/740 but you're aware of it because you also participated in the discussion.
