### ISSUE TITLE
DSN module

### ISSUE THREAD

**Issue by babatoko** [OCA/l10n-france#284]
Is there any chance that we can get a module DSN into oca. Openconcerto seems to get one and I think we should have it.

As I'm not sure how to start I've posted my thought here.

Thank for replying.

**Comment by alexis-via** [comment]
I suppose you're talking about the Déclaration Sociale Nominative. It's part of payroll software. ERPs rarely integrate payroll. On my side, I don't have plans to work on payroll in Odoo. But if you want to start working on payroll, go ahead!
