### ISSUE TITLE
Lot of errors when push on odoo.sh (v13)

### ISSUE THREAD

**Issue by Barronjj** [OCA/l10n-france#300]
Hello,
i downloaded module "French letter of change", added in my local code and then push it on Odoo.sh (development branch)
My project on odoo.sh is in version 13 (latest version)
I obtained many errors (see txt file attached)

Is somenone could explain to me what's happen ?

Regards
Vincent

[Errors.txt](https://github.com/OCA/l10n-france/files/7076557/Errors.txt)

**Comment by legalsylvain** [comment]
Well. Logs says that there is an error on account_invoice_extract module.
Closing as unrelated.

**Comment by legalsylvain** [comment]
Well. Logs says that there is an error on account_invoice_extract module.
Closing as unrelated.
