### ISSUE TITLE
Errors on deploy on Odoo.sh

### ISSUE THREAD

**Issue by Barronjj** [OCA/l10n-france#301]
Hello,

I created a new projet (v13) on Odoo.sh with nothing (no production or staging branch, no customization. Only a dev branch Main)
From the LCR form, i clicked on button "Deploy on Odoo.sh"
it created a new development branch named : app-account_banking_fr_lcr

But i obtained lors of errors that you can see in the file attached
[Errors_20210831.txt](https://github.com/OCA/l10n-france/files/7083152/Errors_20210831.txt)

Could you help me to fix these problems ?
Vincent

**Comment by legalsylvain** [comment]
Please don't duplicate issues. (#300)

If you want to report bugs please reproduce it on OCA runbot instance.
Kind regards.
