### ISSUE TITLE
[l10n_fr_siret] Render siren field unique

### ISSUE THREAD

**Issue by ygol** [OCA/l10n-france#307]
Is there a case where would not want the siren to be unique?

what would be the best way to implement it knowing that some partners could have no siren?
thank you

**Comment by legalsylvain** [comment]
Is there a case where would not want the siren to be unique?

In our odoo implementation, we have a multi company instance, with separated partners, so siren should not be unique (or per company) in our case.

Kind regards.

**Comment by ygol** [comment]
Would that work?
```
_sql_constraints = [

        ('siren_company_uniq', 'unique (siren,company_id)', 'The SIREN must be unique per company !')

    ]
```

thank you

**Comment by alexis-via** [comment]
In v14, in l10n_fr_siret, I implemented a warning when 2 companies have the same SIREN (same warning as when 2 companies have the same VAT, but this warning is still displayed when not in editable mode), cf https://github.com/OCA/l10n-france/blob/14.0/l10n_fr_siret/models/partner.py#L119 This warning appear in a yellow banner similar to https://akretion.com/en/blog/warnings-in-case-of-overdue-invoices

I think this kind of warning is a good solution. Maybe you can backport this feature to your version if you're not on v14.

**Comment by ygol** [comment]
@alexis-via Yes I have the warning. 
I'll close this for now. Tnx
