### ISSUE TITLE
[8.0] Withholding taxes

### ISSUE THREAD

**Issue by lefeverd** [OCA/l10n-france#32]
Hello,

I have a question regarding withholding taxes.
Is it possible to add this type of taxes to a supplier invoice?

I have a customer in France who needs to pay some freelances.
The legislation forces him to retain the taxes from the total of the invoice.

I searched around but did not find anything (except an italian module for the v7).

Thank you,
David

**Comment by alexis-via** [comment]
I don't understand your point. Could you explain it again ? You can explain it in French, because we are all French speakers on l10n-france. I don't understand what you mean by " The legislation forces him to retain the taxes from the total of the invoice.".

**Comment by alexis-via** [comment]
@lefeverd could you answer my question above on this bug report ? Otherwise, we may close it...

**Comment by alexis-via** [comment]
I close this bug report, as we don't understand the issue and the author doesn't answer the question.

**Comment by lefeverd** [comment]
Bonjour,

désolé pour la réponse tardive.
Ma question était relative au principe d'impôt retenu à la source.
Nous avons cependant contourné le problème pour l'instant, cette issue peut donc effectivement être clôturée.

Merci!

**Comment by alexis-via** [comment]
C'est quoi ce truc d'impôt retenu à la source pour les freelances ? Jamais entendu parler de ça.... si tu as un lien à ce sujet, je suis preneur !

**Comment by lefeverd** [comment]
Franchement je ne connaissais pas non plus,
mais d'après ce qu'on m'a rapporté, cela servirait à retenir des taxes sur le paiement d'un fournisseur (freelance).
En gros, sur une partie du montant de la facture du fournisseur (98,25% du brut), on décompte des taxes:
CSG et CRDS (https://fr.wikipedia.org/wiki/Contribution_sociale_g%C3%A9n%C3%A9ralis%C3%A9e)

Qui sont d'après ma compréhension payées à l'agessa: https://www.agessa.org/

J'ai un lien en anglais (oui c'est SAP...): http://help.sap.com/saphelp_byd1411/en/KTP/Software-Components/01200615320100003379/WEKTRA_for_Work_Centers/SRM/Ess/ESS_PRO_WithholdingTaxDetermination.html

Mais tout cela reste un peu flou pour moi.
Et je suppose qu'on pourrait s'en sortir en configurant correctement les taxes dans Odoo.
