### ISSUE TITLE
l10n_fr_siret : SIREN Issue with contact

### ISSUE THREAD

**Issue by omarie-ctc** [OCA/l10n-france#322]
## Module
l10n_fr_siret

## To Reproduce
**Affected versions = v.14**:

1. A company is created with SIREN 000000000 and NIC 00000; (because we don't have immediately the information)
2. A company's contact is created (which will inherit the SIREN and NIC from the company)
3. The company's SIREN and NIC are changed (to 378234595 and 00072);
4. The SIREN is passed down to the contact, but the NIC is not!
5. The contact SIRET is now 37823459500000 (because it inherits the parent's SIREN, but it keeps the old NIC), which is a faulty code.

**Expected behavior**
The change should be taken into account for the company and for the contact who is not a company is an another NIC

**Additional context**

**Comment by alexis-via** [comment]
It doesn't make sense to change then SIREN of a company. If the SIREN changes, it means that it's another moral person, so you have to create another company (and archive the previous company if you want to make it disappear).
I'm OK to block the creation of a partner with SIREN 000000000.

**Comment by omarie-ctc** [comment]
it makes sense when you have a customer on the phone who wants to order but doesn't know their SIRET number. So you create a false SIRET while waiting for it to find the right one so as not to block the order.

**Comment by alexis-via** [comment]
So, let me summurazie the situation: you implemented a constraint to prevent the validation of an order from a French company when SIRET is not set in Odoo. Then, your users found a way to by-pass the constraint by setting a wrong SIREN 000000000. And now, you say that there is a bug in Odoo because you need to change the SIREN of a company... which is something that is never supposed to happen in real life.

I love this kind of bug :)

**Comment by omarie-ctc** [comment]
This is not a bug but rather a functional issue. ;) In real life a customer can order but cannot know the SIRET of his company this does not mean that he should not be allowed to order. It's the case for the company where we install this module.

**Comment by gurneyalex** [comment]
I discussed this with @omarie-ctc  and we will fix this in the custom module which makes the siren / nic required. 

Thanks for your time @alexis-via
