### ISSUE TITLE
Improvement suggestion in l10n_fr_chorus_account for when a siret changes on a res.partner

### ISSUE THREAD

**Issue by unccvince** [OCA/l10n-france#338]
Hello Alexis

**Is your feature request related to a problem?**

Yes, it is a problem if a valid yet wrong siren and nic are entered by error for a chorus partner.

Scenario

1. enter valid siren and nic on res.partner
2. click on fr_chorus_identifier_and_required_button to retrieve chorus related information, **OK**
3. change the siren and nic on the res.partner to another valid siret
4. click again on fr_chorus_identifier_and_required_button, **NOK, the information related to the new siret is not retrieved**.

**Describe the solution you'd like**

On having changed the `res.partner.siret`, a solution would be to either:

1. have the `fr_chorus_identifier_and_required_button` button (1) delete `fr_chorus_service_id` on the `invoice_partner_id`, (2) delete the list of `chorus.partner.service` related to the partner, (3) reset `res.partner.fr_chorus required` & (4) `res.partner.fr_chorus identifier` with the new values related to the new siret.

2. have a new button beside the 'fr_chorus_identifier_and_required_button' button that would (1) set 'res.partner.fr_chorus required' & 'res.partner.fr_chorus identifier' to Null values, (2) delete `fr_chorus_service_id` on the `invoice_partner_id`, (3) delete the list of `chorus.partner.service` related to the partner, so when clicking on the 'fr_chorus_identifier_and_required_button' button, the new correct values for `res.partner.fr_chorus required` & `res.partner.fr_chorus identifier` would be set.

A plus would be a message reminding the user to choose from the new list the new `fr_chorus_service_id` on the `invoice_partner_id`.

Vincent

**Comment by joelgombin** [comment]
I do have the same issue and am completely blocked because I can't invoice a client for which a wrong SIRET was initially input (I changed the SIRET but now can't pull the Chorus services codes).

**Comment by njeudy** [comment]
@alexis-via can we work on this because I can not find why ? Will try to reproduce un a dev environnement !
I think we can reoppen this issue ?
