### ISSUE TITLE
Confirmation of selected company: permission denied for /home/odoo

### ISSUE THREAD

**Issue by asm8073** [OCA/l10n-france#347]
## Module
l10n_fr_siret_lookup

## Describe the bug
Choose a contact for a company. Click on Actions > SIRENE lookup. Select a line from the list, confirm the selection. 
An error messahe appears : 
------------------------------------
User error:
Failed to query VIES.
Technical error: [Errno 13] Permission denied: '/home/odoo'.
------------------------------------

In the log file:
------------------------------------
2022-02-14 10:49:45,705 2241 DEBUG odoo_ecologic odoo.api: call fr.siret.lookup.line(33,).update_partner()
2022-02-14 10:49:45,707 2241 INFO odoo_ecologic odoo.addons.l10n_fr_siret_lookup.models.res_partner: VIES check of VAT FR89738205269
2022-02-14 10:49:45,708 2241 ERROR odoo_ecologic odoo.addons.l10n_fr_siret_lookup.models.res_partner: VIES query failed: [Errno 13] Permission denied: '/home/odoo'
2022-02-14 10:49:45,709 2241 WARNING odoo_ecologic odoo.http: Failed to query VIES.
Technical error: [Errno 13] Permission denied: '/home/odoo'.
------------------------------------

## To Reproduce
**Affected versions**: Odoo 14.0+e-20220110 (Enterprise Edition), l10n_fr_siret 14.0.1.3.1, l10n_fr_siret_lookup 14.0.1.0.0

1. Choose a contact for a company.
2. Click on Actions > SIRENE lookup
3. Select a line from the list
4. Confirm the selection

**Expected behavior**
The selected information should be applied t the contact

**Additional context**
Installation Odoo dans une VM avec l'image Bitnami.

**Comment by legalsylvain** [comment]
Could you provide lines where the errors is done ?
Could you reproduce the big on runboat ?

Thanks

**Comment by asm8073** [comment]
Hi,
As far as I can see in the code of l10n_fr_siret_lookup/models/res_partner.py, the error is produced by this function:
@api.model
    def \_siren2vat_vies(self, siren, raise_if_fail=False):
        vat = "FR%s" % siren_to_vat(siren)
        logger.info("VIES check of VAT %s" % vat)
        vies_res = False
        res = False
        try:
            stdnum_version_float = float(stdnum_version)
        except Exception:
            stdnum_version_float = 1.8
        try:
            if stdnum_version_float < 1.9:
                vies_res = check_vies(vat)
            else:
                vies_res = check_vies(vat, timeout=5)
            logger.debug("VIES answer vies_res.valid=%s", vies_res.valid)
        except Exception as e:
            logger.error("VIES query failed: %s", e)
            if raise_if_fail:
                raise UserError(_("Failed to query VIES.\nTechnical error: %s.") % e)
            return None
        if vies_res and vies_res.valid:
            res = vat
        return res

I have no runboat, I test this on our pre-production platform.

**Comment by asm8073** [comment]
Hello, 
I've tried to add the folders pointed in the error, I've arrived step by step to : /home/odoo/.cache/zeep . At the end, I've got the error : unable to open database file.
Could you tell what the problem is with the zeep library in my case ? I use the bitnami stack for Odoo installation and the zeep library is installed in /opt/bitnami/odoo/venv/lib/python3.8/site-packages/zeep

**Comment by asm8073** [comment]
Bonjour @remi-filament ,
Pourriez-vous regarder le problème avec ce module ? J'ai essayé de creuser mais je ne peux pas aller plus loin. Merci.

**Comment by remi-filament** [comment]
I cannot reproduce this issue, however this error of permission on /home/odoo sounds more like an issue with your installation.

Also I do not use your environment with Odoo Entreprise, so it is hard to guess...

Can you please check that your Odoo user has read/write access to this directory and subdirectories ?
What do you have in this directory, do you only have Python libs or also Odoo filestore ?

**Comment by asm8073** [comment]
@remi-filament Thank you Rémi for your reply. 
My installation does not have such a directory /home/odoo at all, Odoo standard part is installed inside the Bitnami stack in the directory /opt/bitnami/odoo and the enterprise part is installed in another directory. Did you test with Odoo installed in /home/odoo or in another directory as well? 

In order to go as far as I could in understanding the problem, I've created the directory /home/odoo and then .cache an then zeep, following the error messages I got. I've done to these folders the same permissions as for other Odoo directories : bitnami:odoo. 

Could you help me to understant why the module points out the /home/odoo directory while there was no Odoo installation there ? I would expect that the module uses the actual Odoo installation path instead of something predefined. Or, is it the zeep library installation issue which the l10n_fr_siret_lookup module depends on?

**Comment by remi-filament** [comment]
Hi, for me this module is not pointing anywhere, it just tries to connect to external API ans use stdnum lib to check VAT number with VIES service.
Have you tried without this module installed if you get the same error ?

Le February 24, 2022 8:45:16 AM UTC, asm8073 ***@***.***> a écrit :
***@***.*** Thank you Rémi for your reply. >

**Comment by asm8073** [comment]
Hi Rémi,
I cannot try confirmation of the SIRET without the SIRET module installed, the use case just does not exist without the module. 
Concerning the module, it seems to use the sqlite for some data and this makes a problem, as I reported above.
Are you able to reproduce the error using Bitnami Odoo image ?

**Comment by remi-filament** [comment]
Hi @asm8073 
sorry for the delay in answering, this Bitnami image is really far from the environment we usually run on. Nevertheless we tried to install it and did not find where the problem could be.
I am sorry that we have not much more time to spend on this issue which seems related to this very specific environment (since working properly for us, our customers and others).

Also I am not sure why you refer to sqlite, which is absolutely not needed for this module to run (we do not even have it installed on our servers), although I have seen that it is part of Bitnami installation but not sure why...)

**Comment by asm8073** [comment]
Hi @remi-filament ,
Thank you for your efforts. I've not understood from your answer whether you have managed to use the odule on Bitnami image or not. 

Could you please confirm if it works for you on Bitnami or not ? 

As for Bitnami, it is a reference in the VM images distribution and allows to securise the installations. Sure, it may be specific, but we have been running Odoo on Bitnami images since 3 years and Odoo never complained about this environment. Anyway, I suppose that the module for Odoo has to work wherever Odoo is able to work, right ? But the error I've got shows clearly that it expects Odoo in some (hardcoded?) path (/home/odoo instead of /opt/bitnami/odoo) and it is first time I see such an error after having a module installed for our Odoo (and I've tried a lot of them).
As for sqlite, it has appeared when I've tried to create all missing folders (/home/odoo/.cache/zeep) reported by the module in its errors.
