### ISSUE TITLE
We can' use runboat

### ISSUE THREAD

**Issue by omarie-ctc** [OCA/l10n-france#350]
## Module
l10n_fr_intrastat_product

## Describe the bug
We can't try on runboat this module

@sbidoul could you please take a look why runboat doesn't work ?

Thanks !

**Comment by legalsylvain** [comment]
I just tried runboat and it works. 
could you provide step to reproduce ? 
thanks !

**Comment by omarie-ctc** [comment]
Sorry for the lack of detail.
I'm trying to use runboat l10n_fr_intrastat_product for v12 branche. 
> So I go to v12 branch
> In l10n_fr_intrastat_product
> I click on ''try me''

And every runboat are in red and we can't use it.
It's here :
https://runboat.odoo-community.org/webui/builds.html?repo=OCA/l10n-france&target_branch=12.0

Thanks for your help.

**Comment by gurneyalex** [comment]
The error during the build is 

odoo.exceptions.UserError: ('Modules "Account e-invoice Generate" and "Import Vendor Bills From XML" are incompatible.', '')

**Comment by sbidoul** [comment]
Was it not fixed in some branches at least ?
