### ISSUE TITLE
Failed to install department module

### ISSUE THREAD

**Issue by captivea-cmi** [OCA/l10n-france#356]
module: l10n_fr_department
version: 14.0

**Steps to reproduce**
- I'm trying to install the department module on an enterprise version v14 on an on-premise server
- I downloaded the "French Departments" module from apps.odoo.com via the button "download for v14" 
- In my basis, in developer mode, I go to the "apps" module and click on the "install a module" button
- I click on "upload your file" and select the zip file that I downloaded
- I click on "import"
- (I also try another time to enable "Force init" but the result is the same)

**Current behavior**
- I have this error message:
"Successfully imported module 'l10n_fr_state'
Error while importing module 'l10n_fr_department'.

 Module loading l10n_fr_department failed: file /tmp/tmplsnyvq4h/l10n_fr_department/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_res_country_department' in field 'Model'
No matching record found for external id 'model_res_country_department' in field 'Model'
Missing required value for the field 'Model' (model_id)
Missing required value for the field 'Model' (model_id) 
 Make sure those modules are installed and try again."

**Expected behavior**
- The module should install succesfully

**Comment by legalsylvain** [comment]
Hi. the module ``l10n_fr_department`` works correctly on runboat. (just tested)

So this is a deployment error unrelated to this module.

kind regards.
