### ISSUE TITLE
[14.0]l10n_fr_department conflict with res_partner_department

### ISSUE THREAD

**Issue by flotho** [OCA/l10n-france#384]
trying to install https://github.com/OCA/partner-contact/blob/14.0/partner_contact_department/models/res_partner.py#L11 and l10n_fr_department in the same db cause issues.

what is the process to deal with this when 2 fileds with the same name are not referencing the same comodel?

**Comment by legalsylvain** [comment]
There is no way. For the time being, both module are incompatible.
One solution could be to rename the field in the current module to another one.
But you have to add migration script. quite a mess.

**Comment by flotho** [comment]
as a starting point, is there any options in the manifest that could prevent the double installation ?

**Comment by alexis-via** [comment]
For v14, I made a PR to declare a conflict in the manifest.
For v16, we could change the name of the field "department_id" on res.partner. What about "country_department_id" ? Feel free to propose a better field name.
