### ISSUE TITLE
Error 403 updating chorus info and services

### ISSUE THREAD

**Issue by Auneor** [OCA/l10n-france#410]
module: l10n_fr_chorus_account
version: 14.0

**Steps to reproduce**
I've done all the Configuration steps, and when I click on "Update chorus information and services" on customer tab

**Current behavior**
I get the error:
"Wrong request on https://sandbox-api.aife.economie.gouv.fr/cpro/structures/v1/rechercher. HTTP error code received from Chorus: 403"
Logs say:

odoo.addons.l10n_fr_chorus_account.models.company:Requesting new token from PISTE via https://sandbox-oauth.aife.economie.gouv.fr/api/oauth/token
odoo.addons.l10n_fr_chorus_account.models.company:New token retreived with a validity of 3600 seconds
odoo.addons.l10n_fr_chorus_account.models.company:PISTE token expires on 2023-01-20 11:34:01.588083 GMT (includes margin)
odoo.addons.l10n_fr_chorus_account.models.company:Chorus API POST request to https://sandbox-api.aife.economie.gouv.fr/cpro/structures/v1/rechercher with login XXX@XXX.XX
odoo.addons.l10n_fr_chorus_account.models.company:Payload of the Chorus POST request: {'structure': {'identifiantStructure': 'GOODSIRETNUMBER', 'typeIdentifiantStructure': 'SIRET'}}
ERROR:odoo.addons.l10n_fr_chorus_account.models.company:Chorus API webservice answered with HTTP status code=403 and content=
WARNING:odoo.http:Wrong request on https://sandbox-api.aife.economie.gouv.fr/cpro/structures/v1/rechercher. HTTP error code received from Chorus: 403

**Expected behavior**
No error

**Comment by alexis-via** [comment]
Haha, the cause of the bug is probably in your logs, see 'identifiantStructure': 'GOODSIRETNUMBER', !!!

**Comment by Auneor** [comment]
Hi @alexis-via ,
It was just me that anonymized the siret for this ticket, but thanks, we could figure out what was the problem, it was a misuse of the "matelas de données", we had to log with login compte GP" et "mot de passe compte GP" and do the raccordement  and it worked.
Thanks anyway for your great job :)
