### ISSUE TITLE
Remaining bug when creating a refund for a chorus invoice

### ISSUE THREAD

**Issue by unccvince** [OCA/l10n-france#411]
## Module

l10n-france/l10n_fr_chorus_account/models/account_move.py

## Describe the bug

Around line 285 in v12

`        elif self.move_type == "out_refund":
            if self.payment_mode_id:
                raise UserError(
                    _(
                        "The Payment Mode must be empty "
                        "for customer refunds sent to Chorus."
                    )`

The `payment_mode_id` is transfered from the invoice to the refund when refunding the invoice.

Exceptionnally, when refunding a Chorus type invoice, the `payment_mode_id` **MUST** be set to Null.

Here the refund invoice can not be validated because the `payment_mode_id` **IS NOT** set to Null before raising the error.

## To Reproduce

In V12.

1. Create an invoice for a customer having `payment_mode_id` = *chorus*.
2. Create a refund for the invoice, the error message will display and the refund invoice is not created.

**Expected behavior**

A refund invoice should be created having `payment_mode_id` = *Null*.

**Comment by alexis-via** [comment]
I agree it can be improved. Please create a PR to fix this.
