### ISSUE TITLE
FEC file not generated, error "Connection lost, trying to reconnect"

### ISSUE THREAD

**Issue by Nicolas-NCS-DD** [OCA/l10n-france#415]
## Module
France - FEC Export

## Describe the bug
When we try to export a FEC file, if we use more than 2 or 3 months, export is not created. A message appears "Connection lost, trying to reconnect", and in odoo.log file we can see
2023-02-13 09:30:31,456 0 ERROR avalahee-dessus-dessous-15-staging-customer-6403343 odoo.sh: Worker process (pid=4) was killed by signal 9 (most likely hit a memory limit, please check your custom modules memory usage.)

"Test" checkbox as checked every time.

We know that we have an issue in our contacts creation, meaning that each time a same customer places an order in our CMS, Odoo is creating a new contact. So I'm not telling FEC Export has a bug, but I want to be sure that solving multi-customer creation will help here. Can it be the root cause of FEC file not generated ? (because of too much contacts to search for)

## To Reproduce
**Affected versions**:
we are working on a v15 of Odoo

1.go to Acounting > Reporting > FEC
2.select start date (06/01/2022) and end date (12/31/2022), check the "Test" box
3.click on Generate, wait for less than 30 seconds, then message "Connection lost..."

**Expected behavior**
I'm expecting FEC file to be exported or at least to find informations on what happen, to be able to fix root cause

**Additional context**

**Comment by alexis-via** [comment]
In your odoo server config file, you must increase the values for:

limit_time_cpu
limit_time_real
limit_memory_hard
limit_memory_soft
