### ISSUE TITLE
[14.0] [l10n_fr_fec_oca] psycopg2.errors.GroupingError: column « aat.id »

### ISSUE THREAD

**Issue by gaelTorrecillas** [OCA/l10n-france#427]
Hello, 

We have a bug with FEC export. (Invoice/report/FEC)
when we export FEC with the last version, we have this error : 
the column "aat.id" must appear in the GROUP BY clause or must be used in an aggregate function

after some research, I find this line : 
https://github.com/OCA/l10n-france/pull/396/files#diff-2840652b55f1916fd003b3330417dde95573fb1e5fe01191769b7fe9ce1275e1R211

We have the aat.id and partner_account_type_ids must be required, same one value, we have this error.

**Comment by alexis-via** [comment]
Fixed
