### ISSUE TITLE
Multi-localisation: hide fields that are only for French localisation

### ISSUE THREAD

**Issue by alexis-via** [OCA/l10n-france#461]
In the French localization modules, we sometimes add fields on partners, fiscal position or taxes. Not a lot, but some modules do add some (l10n_fr_siret, l10n_fr_das2, l10n_fr_account_vat_return, etc). In a multi-localization environment, these fields "pollute" the view for the Odoo users in another country. For l10n_fr, there is a discussion about this in https://github.com/odoo/odoo/issues/125167

In Saas 16.2, in the official l10n_fr module, when they add the siret field on res.partner form view, they add an invisible condition like this:
```
attrs="{'invisible': ['|', ('fiscal_country_codes', 'not ilike', 'FR'), ('is_company', '=', False)]}"
```
https://github.com/odoo/odoo/blob/master/addons/l10n_fr/views/l10n_fr_view.xml#L26
'fiscal_country_codes' is a related field defined in the "account" module:
https://github.com/odoo/odoo/blob/master/addons/account/models/partner.py#L37
account_fiscal_country_id is a field of res.company defined in the "account" module : 
https://github.com/odoo/odoo/blob/master/addons/account/models/company.py#L145
account_fiscal_country_id is present on the Accounting config page:

![fiscal_country](https://github.com/OCA/l10n-france/assets/1157917/3657a45f-c262-4c63-b2c1-90d420132ed0)

For the fields on partner, the fact that the visibility condition is linked to the country of the partner or the country of the company depend on the field itself. For me, the difficult question is about the multiple ISO country codes we have for the France, where we have ISO 3166 codes for French oversea territories. So, should we have
```
attrs={'invisible': [('country_code','!=', 'FR')]}

```
or should we have:
```
{'invisible': [('country_code', 'not in', ('FR', 'GP', 'MQ', 'GF', 'RE', 'YT', 'NC', 'PF', 'TF', 'MF', 'BL', 'PM', 'WF'))]}
```
What do you think @cvinh ? For a company or partner in pylynesia, do you use "base.pf" for the "country_id" field, or "base.fr" ?

**Comment by alexis-via** [comment]
Idea by @sebastienbeau : inherit the compute method of the field account_fiscal_country_id on res.company: if the field country_id of res.company is part of the DOM-TOM res.country.group (cf https://github.com/odoo/odoo/blob/16.0/addons/l10n_fr/data/res_country_data.xml#L2), then set account_fiscal_country_id to base.fr

**Comment by cvinh** [comment]
In French Polynesia, we use base.pf in country_id.
About DOM-TOM, it's an old concept. Nowadays, we say POM (Pays d'Outremer) for NC, PF and a lot of others... Here is a non official source that gives you an idea https://www.axl.cefan.ulaval.ca/francophonie/dom-tom.htm

In PF we don't have Siret, the identifier is 'Numero Tahiti'. In 2025, we plan to have a SIRET in addition to the 'Numero Tahiti' but it will no replace it.
We do have a RCS number like in FR.

Actually, we prefer not using l10n_fr for accounting but some modules of l10n-france can be interesting
