### ISSUE TITLE
Generalization/Internationalization of l10n_fr_ecotaxe

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-france#483]
Hi! Probably not the right place to ask about this...

Here in Italy we manage some excise duties in the very same way you manage ecotaxes.
I believe the same happens in other countries where excises are used to tax the import/export of special products like alcohol, batteries, petroleum derivatives or in general taxes base on weight, volume or other attributes.

Should we generalize the way OCA manage such taxes so each l10n-* project would share part of the code?

Cheers!

**Comment by legalsylvain** [comment]
CC : @alexis-via could you take a look on this one ? 
thanks !

**Comment by bealdav** [comment]
It seems to be a nice idea @mourad-ehm @alexis-via

**Comment by bealdav** [comment]
Maybe we could put ecotax module here https://github.com/OCA/account-fiscal-rule

**Comment by bealdav** [comment]
We now use account.tax for ecotax

https://github.com/OCA/account-fiscal-rule/pull/428 
https://github.com/OCA/account-fiscal-rule/pull/429

It's wip.

Could you have a quick look into.

cc @legalsylvain @dcorio

**Comment by legalsylvain** [comment]
Hi @bealdav. No need to ping me on that topic. I don't use ecotax. (and really don't know how it works !) 
This one is for @akretion team !

**Comment by rvalyi** [comment]
the work is largely done already in thr OCA/account-fiscal-rules repo. You can follow it here https://github.com/OCA/account-fiscal-rule/issues/453

I think this one can be closed meanwhile.
