### ISSUE TITLE
l10n_fr_siret: access rights issue in multi-company environnement

### ISSUE THREAD

**Issue by alexis-via** [OCA/l10n-france#49]
I have a difficult bug on l10n_fr_siret in multi-company environnement. It's an old bug ; I have it since the beginning on one of my projects that went to production on 1/1/2015 in a multi-company environnement, but I didn't report it at the time.

In certain very particular conditions that I still don't identify properly, you get this kind of error message when you register a payment manually on a customer invoice via the button "Register payment":

```
L'opération demandée ne peut pas être effectuée en raison de la politique de sécurité. Veuillez contacter votre administrateur système. Type de document: res.company. Opération: read.
```

The bug seems linked to the field 'siret' on res.company, which is a related field with Store=True. There are some problems with these related field on objets with a multi-company record-rule that are related to an object which is not company-specific. In this case:
- the 'siret' field on res.company is a field related='partner_id.siret' and store=True field
- there is a record rule on res.company
- res.partner doesn't have any multi-company record rule
  This kind of things raises some issues in multi-company environements: https://github.com/odoo/odoo/issues/9450

And the problems also seems to be linked to the sync of fields from contact to company, cf
https://github.com/OCA/l10n-france/blob/8.0/l10n_fr_siret/partner.py#L85

My workaround for this bug for the moment is to disable the inherit of the method "_commercial_fields".

This bug is very difficult to reproduce, but, when you find an invoice that has the bug when you register a payment, then it becomes 100% reproductible.

**Comment by clonedagain** [comment]
Can you make an automatic test we could integrate in the test suit please?

**Comment by clonedagain** [comment]
if `_commercial_fields` is involved, maybe there is a subtle incompatibility with the v7 API in super()?

**Comment by alexis-via** [comment]
I'd love to make an automated tests... but I still don't when what is the condition that triggers the bug. But I have a dump of the DB of my customer who was impacted and that has one open invoice that triggers the bug when you click on "Register payment". So I need to come back on this bug and continue to work on this bug with this DB. I'll do that as soon as I have time.

**Comment by alexis-via** [comment]
@clonedagain Do you use odoo in a multi-company setup at Numerigraph ?

**Comment by clonedagain** [comment]
not yet, sorry

**Comment by alexis-via** [comment]
I feel we don't have this problem any more on v10+ thanks to related_sudo=True and other improvements.
