### ISSUE TITLE
Private Key Configuration in l10n_fr_account_vat_return_teledec

### ISSUE THREAD

**Issue by zuher83** [OCA/l10n-france#491]
**Description:**
In the README of the l10n_fr_account_vat_return_teledec module for Odoo, the module's @alexis-via recommends adding a teledec_private_key entry to the Odoo Server configuration file, using the private key provided by Teledec.

However, a problem arises when multiple databases are hosted on the same server, as each database requires its own private key. Storing the key in the Server configuration file makes it global, which can lead to conflicts.

**Proposed Solution:**

- Consider storing the private key in res.company to make it specific to each company.
- Address the issue of multi-company environments to ensure proper key management.

Implementing this change would enhance the module's usability in scenarios where multiple databases exist on the same server or in multi-company environments.

Is there a specific reason for the key to be in the config file that I may not have considered?

**Comment by alexis-via** [comment]
You'd better use the same teledec private key for several companies, to benefit from the volume discounts of teledec. I did that on purpose.
