### ISSUE TITLE
l10n_fr_chorus_account > lack of precision in settings/usage

### ISSUE THREAD

**Issue by gregory-moka** [OCA/l10n-france#504]
## Module
`l10n_fr_chorus_account`.

## Describe the bug
Hello @alexis-via . We tried to set this addon, but something is missing cause we have error while transmitting to CPP.
Everything works to get structures information with Siret.
But as we send invoices, we systematically get the same issue from Chorus : 
`Libellé erreur : L'element (AppliedTradeAllowanceCharge.ActualAmount.value) est obligatoire si l'element (SupplyChainTradeTransaction.IncludedSupplyChainTradeLineItem.SpecifiedLineTradeAgreement.GrossPriceProductTradePrice) est renseigne. |L'element (AppliedTradeAllowance [...]`

Here the extract of the xml file : 
```xml
<rsm:SupplyChainTradeTransaction>
...
    <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>2</ram:LineID>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:Name>Product</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:GrossPriceProductTradePrice>
          <ram:ChargeAmount>9.35</ram:ChargeAmount>
        </ram:GrossPriceProductTradePrice>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>9.35</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="C62">12.0</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>S</ram:CategoryCode>
          <ram:RateApplicablePercent>20.0</ram:RateApplicablePercent>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>112.20</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>
...
<rsm:SupplyChainTradeTransaction>
```

## To Reproduce
**Affected versions**:
`16.0`

1. Read the entire README file
2. Set those values in settings : 
![image](https://github.com/OCA/l10n-france/assets/45974412/9fe05267-cf6b-46e7-b60c-0545960553c2)
![image](https://github.com/OCA/l10n-france/assets/45974412/02550a43-25ef-4442-ab81-94e3e1d18e14)

3. Send invoice by clicking on "Send to chorus" button, refresh the feed, and get this error

Thanks for help.

**Comment by gregory-moka** [comment]
@alexis-via up 😄

**Comment by OdooConsultant** [comment]
Hello, please, I need a little explanation. 
Why, in the code of Chorus, if a user has a parent, then we can't send it? 
If in my Odoo, the contact has a SIRET and the parent also has a SIRET, can I send it to Chorus?

 for partner in self.filtered(lambda p: not p.fr_chorus_identifier):
            if partner.parent_id:
                if raise_if_ko:
                    raise UserError(
                        _("Cannot get Chorus Identifier on partner '%s'.")
                        % partner.display_name
                    )
                else:
                    logger.warning(
                        "Skipping partner %s: not a contact", partner.display_name
                    )
                    continue
