### ISSUE TITLE
l10n_fr_siret: Allow invalid SIRETs

### ISSUE THREAD

**Issue by houzefa-abba** [OCA/l10n-france#509]
I know this sounds hazy, but hear me out

When connecting a test Odoo environment with [Chorus Pro qualification](https://communaute.chorus-pro.gouv.fr/documentation/chorus-pro-qualification-portal/?lang=en), one must use SIRET numbers generated by Chorus Pro qualification.
The issue here is Chorus Pro qualification generates invalid SIRET numbers, for example:
* `28050413563341`
* `75454412064565`

These numbers are rejected by the [`l10n_fr_siret`](https://github.com/OCA/l10n-france/blob/16.0/l10n_fr_siret) module; we cannot set them onto our test Odoo partners.

Therefore, when one wants to test the [`l10n_fr_chorus_account`](https://github.com/OCA/l10n-france/tree/16.0/l10n_fr_chorus_account) module, the only solution is setting these SIRET numbers via SQL queries. This of course gets cumbersome depending on how these test Odoo instances are deployed.

Ideas:
1. Create module `l10n_fr_chorus_account_qualification` to disable SIRET validation
1. Add a global setting in `res.config.settings` where one can temporarily disable SIRET validation
1. Add a per-partner setting to be able to say a specific partner has an invalid SIRET on purpose

Thoughts? @alexis-via

**Comment by legalsylvain** [comment]
Hi @houzefa-abba. Thanks for reporting ! 
Did you tried the the option "Contact chorus pro" to ask them to fix the bad number ?
I mean, I see it weird to add extra complexity in a Odoo module, because an entity does'nt respect a nomenclature. Don't you think ?

**Comment by houzefa-abba** [comment]
> Hi @houzefa-abba. Thanks for reporting ! Did you tried the the option "Contact chorus pro" to ask them to fix the bad number ? I mean, I see it weird to add extra complexity in a Odoo module, because an entity does'nt respect a nomenclature. Don't you think ?

Ye I agree it's weird, good idea will ask, maybe they can fix on their side!

**Comment by legalsylvain** [comment]
> Ye I agree it's weird, good idea will ask, maybe they can fix on their side!

:+1: 

note, if they aren't agree to fix the bug, you can calso create a module l10n_fr_chorus_account_qualification that you can install or enable via --server-module option, to disable the feature when you want.

The idea to add complexity and code to disable a must have feature in the main module, because third API in test environment uses invalid SIRETs doesn't seem to me the best option.

**Comment by houzefa-abba** [comment]
> > Ye I agree it's weird, good idea will ask, maybe they can fix on their side!
> 
> 👍
> 
> note, if they aren't agree to fix the bug, you can calso create a module l10n_fr_chorus_account_qualification that you can install or enable via --server-module option, to disable the feature when you want.
> 
> The idea to add complexity and code to disable a must have feature in the main module, because third API in test environment uses invalid SIRETs doesn't seem to me the best option.

Good idea I just added it in the idea list in my first message
