### ISSUE TITLE
l10n_fr_fec_oca is not working

### ISSUE THREAD

**Issue by PlantBasedStudio** [OCA/l10n-france#534]
## Module
l10n_fr_fec_oca

## Describe the bug
There is no "reporting" category in the invoice module when this module is installed. It is therefore impossible to generate a report.

## To Reproduce
Open the runboat and check invoicing

**Comment by PlantBasedStudio** [comment]
I've just learned how to use it. Unfortunately the documentation is too light to understand the FEC system. Whether on odoo itself or on the OCA.

**Comment by legalsylvain** [comment]
Hi @PlantBasedStudio. Thanks for your interest. Feel free to improve documentation, making a PR to change the fragment files present here : https://github.com/OCA/l10n-france/tree/16.0/l10n_fr_fec_oca/readme

regards.
