### ISSUE TITLE
9.0 build is red

### ISSUE THREAD

**Issue by gurneyalex** [OCA/l10n-france#54]
This seems to be related to odoo#9708 

I checked in  https://travis-ci.org/gurneyalex/l10n-france/builds/97396540  that @rco-odoo's patch in https://github.com/odoo/odoo/pull/9896 fixes the situation and proposed to port that fix in  https://github.com/OCA/OCB/pull/404 to at least get a clean situation on OCB.

**Comment by lepistone** [comment]
odoo/odoo#9896 is now merged

**Comment by alexis-via** [comment]
Build is green on v9
