### ISSUE TITLE
l10n_fr_chous_fractur-x > URL API change (info)

### ISSUE THREAD

**Issue by gregory-moka** [OCA/l10n-france#548]
**Futur change**
This mail as been sent to all PISTE users : 
Communication PISTE
Rappel :  Décommissionnement des URL API *.aife.economie.gouv.fr
Bonjour,
 
Comme nous vous l'avons rappelé lors des dernières communications et sur le portail PISTE ici, les URL d'accès PISTE en aife.economie.gouv.fr ne doivent plus être utilisées et doivent être remplacées comme suit :
 
- Pour le portail PISTE
https://developer.aife.economie.gouv.fr est remplacé par https://piste.gouv.fr
 
- Pour la consommation des API
https://api.aife.economie.gouv.fr est remplacé par https://api.piste.gouv.fr
 
- Pour l'obtention jeton d’accès API
https://oauth.aife.economie.gouv.fr/api/oauth/token est remplacé par https://oauth.piste.gouv.fr/api/oauth/token
 
- Pour la consommation API Sandbox (Bac à Sable)
https://sandbox-api.aife.economie.gouv.fr est remplacé par https://sandbox-api.piste.gouv.fr
 
- Pour l'obtention jeton d’accès API Sandbox (Bac à Sable)
https://sandbox-oauth.aife.economie.gouv.fr/api/oauth/tokenest est remplacée par https://sandbox-oauth.piste.gouv.fr/api/oauth/token
 
L'opération de décommissionnement sera planifiée très prochainement.
 
Aucune redirection ne sera mise en oeuvre et aucun retour arrière n'est prévu.
 
Nous vous remercions de bien vouloir relayer cette information importante auprès de vos consommateurs/partenaires, qui ne pourront plus accéder aux services API de PISTE après cette opération, s’ils n’ont pas pris en compte les nouvelles URL.
 
Merci également de supprimer ces URL de vos éventuels favoris et les remplacer par les nouvelles URL équivalentes.
 
Si vous utilisez d'ores et déjà les nouvelles URL, merci de ne pas tenir de ce rappel.
 
Cordialement,
 
Equipe PISTE

**Comment by gregory-moka** [comment]
@alexis-via : Is there something we can do for help ?

**Comment by alexis-via** [comment]
Don't worry, Akretion already did the work to update the URL, cf our blog post:

https://akretion.com/fr/blog/module-pour-lapi-chorus-a-mettre-a-jour-avant-le-30-septembre-2023?tag=
