### ISSUE TITLE
l10n_fr_department: Specific case in department computation for res.partner

### ISSUE THREAD

**Issue by mehdi-ghezal** [OCA/l10n-france#88]
I notice a very small bug in department computation for res.partner ; it supposed that the begin of the zip code can be use for find the corresponding department. It's true for 99%, but in fact there are some exceptions: https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement

**Comment by alexis-via** [comment]
Arf, funny !

You can propose a PR to fix this in l10n_fr_department with the hard-coded list of zip codes taken from wikipedia...

**Comment by alexis-via** [comment]
Fixed in v14. Feel free to back port the fix to earlier versions.
