### ISSUE TITLE
[10.0] Manage french ecotax

### ISSUE THREAD

**Issue by mourad-ehm** [OCA/l10n-france#94]
I proposed a module to manage french ecotax in v8 : #76 

After discussion with @alexis-via,  we propose to make this enhancement for 10.0.
## **Context :**

Definition of ecotax :
An Ecotax (short for ecological taxation) is a tax levied on activities which are considered to be harmful to the environment and is intended to promote environmentally friendly activities via economic incentives (source https://en.wikipedia.org/wiki/Ecotax).

There are 2 levels to manage ecotax :
1) basic level :  consider the sale ecotax as a field of the product (fields.Float()).

This field should be displayed on the invoice lines (sale line and purchase line) ("included ecotax amount").
The price of the product should include ecotax . For exemple if the original product price = 100€ and ecotax = 1€ product price should be update to 101€. 
Then add a function field on account.invoice named "total_ecotax_amount". 
The total ecotax amount is the sum of ecotax amount line.
This field "total_ecotax_amount" should be displayed on the invoice (sale, purchase).

To declare and transfer to the ecotax company,  you can simply use the BI features on invoices to get the sale ecotax amounts.

2) Advanced level : consider ecotax as a regular tax : like in PR #76 (module used in production for an akretion customer)

consider ecotax as a regular tax. We can use separate accountant account for ecotax.
The goal is not to have one tax for each amount, but one tax for all amounts. Then, the amount of tax (in account.tax) are computed by using python code (value taken from product ). 
ecotax must have a sequence lower than VAT tax and must be included in tax. 

To make this we should add : 
- new type of account.tax,
- a field on product that contains ecotaxe value of product (or computed value for weight base ecotax),
- set the new taxes (ecotaxe) on product, 
- a computed field on invoice (sale, purchase) line that display ecotax,  
- a total mount ecotax field on invoice (sale and purchase)

  In this feature we also manage a weight based ecotax (For furnitures (desk, table, wardrobe, ...)).
  To simplify handling weight based ecotax, we should add an ecotax classification object. This object contains different rates applied on based weight ecotax as well as different  fixed ecotax amounts (classification may be : "fixed" or "weight based"). It also contains taxes used to compute ecotax amounts.
 With this approach, you have a separate accounting account for the ecotax, so you can directly know in the accounting how much you have to transfer to the ecotax company.

## Solution proposed :

So, we propose to make 2 modules : 
1-  l10n_fr_base_ecotax
2- l10n_fr_advance_ecotax

the advance module inherits form the base module.

### Features:
    
**Base module**
 - Fixed ecotax only (a field on product)
 - ecotax amount on sale line, purchase line and invoice line (for display purpose because de ecotax amount are include in the price of product in the basic approach) 
 - Total ecotax amount on sale, purchase and invoice
 - Value off ecotax are propagated to invoice from sale or purchase order.

**Advanced module**
 - Fixed and weight based ecotax,
 - ecotax classification to factorise value (several product has the same rate)
 - use account.tax to compute ecotax and define an accountant account (product price don’t contains ecotax):
         Type = 'code' ; python code contain this : 
 ** result = product.fixed_ecotax or  0.0  (for tax used for fixed ecotax  ; Account ex :  sale ecotax 707110, purchase ecotax 607110 )
 ** result = product.computed_ecotax or  0.0  (for tax used for fweight based ecotxe; Account ex :  sale ecotax 707120, purchase ecotax 607120)
 ** Include_base_amount = True
 ** Sequence less then VAT tax (ex 0)
  ** Add a field, is_ecotax = True
 - Sale, purchase, and invoice line contain a computed field that compute ecotax by using taxes (with is_ecotax = true).
 
### Design:
    
**Base module**
  - Add a field fixed_ecotax = fields.Float to product_product.
 - Display this field on the invoice line (sale line and purchase line) ("included ecotax amount"),
 - Add a function field on account.invoice named "total_ecotax_amount". that is computed with :
 -  Add  total_ecotax

total_ecotax = 0.0
for l in line:
    total_ecotax += l.quantity * l.product_id.ecotax_amount
self.total_ecotax_amount = total_ecotax

 - Display the field "total_ecotax_amount" on the invoice (sale, purchase).

**Advanced module**
 - Manage fixed (ex electronic devices) and a weight based ecotax (For furnitures (desk, table, wardrobe, ...))  
 - Add an object ecotax classification that contains ecotax amount or rate to apply for weight (type = fixed, or weight based)
 - On product product : 
    * add a link to ecotax classification,
    * add computed field that compute value by using ecotax classification.
 - Add a field is_ecotax on  account.tax. 
 - The ecotax must be defined as  python code : 
ecotax must have a sequence lower then VAT tax and must be included in tax. 
 - The sale ecotax as a property of the product (fields.Float(company_dependant=True)). 
 - The amount of tax (in account.tax) are computed by using type python code ( use module account_tax_python)
 - Add computed field on invoice (sale, purchase) line that display the total Amount ecotax.

### Use Case:
-  ecological taxation called ecotax in France
-  Eco contribution (wieght based tax) in France

### Proposal for module name :
 - l10n_fr_base_ecotax
 - l10n_fr_advance_ecotax

**Comment by matmicro** [comment]
Hi,

Is this module (ecotax) source code available for Odoo 10 ?

Thanks and regards

**Comment by rvalyi** [comment]
@matmicro 
stay tuned here as I' will very soon publish a v12 module that deal with these requirements. I should do it this week. I will propose it to the OCA (you could then easily backport it to v10 or Akretion may do it for you).

**Comment by matmicro** [comment]
@rvalyi Ok thanks.
Could be great if it will be available to v10.

What are the main differences between v10 and v12 source code ? (in order to understand how to backport it)

Thanks and regards

**Comment by matmicro** [comment]
@rvalyi any update on this ?
Did you release the module ? Ca you peovide a link ?

Thanks and regards

**Comment by mourad-ehm** [comment]
Hi @matmicro, 
Yes there is 3 PR for odoo 14, 12 and 8:
https://github.com/OCA/l10n-france/pull/242
https://github.com/OCA/l10n-france/pull/271
https://github.com/OCA/l10n-france/pull/279
