### ISSUE TITLE
[FEC] Mise en conformité

### ISSUE THREAD

**Issue by fmdl** [OCA/l10n-france#99]
The text is will be in french, because it is an issue for only french company.
author of l10n_fr_fec : @alexis-via 

Bonjour

Suite à l'intervention de notre expert comptable il est apparue quelque questions, améliorations, afin d'être en conformité avec la loi. https://www.legifrance.gouv.fr/eli/arrete/2013/7/29/BUDE1315492A/jo/texte
- L'article 2, impose de fournir une description incluant :
`« 1° Le nom, la nature et la signification de chaque zone ;
« 2° La signification des codes utilisés comme valeurs de zone ;
« 3° Toutes les informations techniques nécessaires au traitement des fichiers, et notamment le jeu de caractères utilisé, le type de structure, la longueur des enregistrements, les caractères séparateur de zone et séparateur d'enregistrement.`
La creation d'un PDF incluant notamment la ligne 3°, à télécharger depuis le wizard serait un début de solution.
- Les expert-comptables ont un nouveau logiciel de verification de FEC sous la forme de macro VBA, qui a des problèmes de lecture si il y a des tabulations dans les champs, il doit prendre en compte les deux délimiteurs tab et pipe sur le même fichier. Dans le script Odoo est-il possible de faire en sorte que les tabulations soient supprimées.
- Notre experts comptable ne peut pas importer le FEC dans son logiciel d'analyse, car les comptes auxiliaires sont indiqués sur tout les comptes, alors que d'après notre expert, il ne devrait être que sur les 401, 411. D'après la loi il n'est explicitement indiqué les comptes à exclure (ou à inclure) d'avoir un compte auxiliaire. Afin de faciliter le travail de ces derniers, le rajout d'un champs des comptes avec compte auxiliaires dans le wizard serait-il possible ? Dans l'exemple de ce document seul les comptes 401,411 sont montrés : http://bofip.impots.gouv.fr/bofip/ext/pdf/createPdfWithAnnexePermalien/BOI-CF-IOR-60-40-20-20131213.pdf?doc=9028-PGP&identifiant=BOI-CF-IOR-60-40-20-20131213
- La date de lettrage indiqué dans Odoo est celle du jour où est réalisé le lettrage. Or cette note http://www.suiteexpert.fr/public/documents/awcompta/A47_AnnexeTechnique.pdf, serait plutôt d'avis a indiquer la date du plus vieux mouvement. Qu'en pensez-vous ?

**Comment by fmdl** [comment]
https://github.com/odoo/odoo/issues/15781

**Comment by alexis-via** [comment]
Le 09/03/17 à 09:02, Florent de Labarre a écrit :
> L'article 2, impose de fournir une description incluant :
>
>   * |« 1° Le nom, la nature et la signification de chaque zone ; « 2°
>     La signification des codes utilisés comme valeurs de zone ; « 3°
>     Toutes les informations techniques nécessaires au traitement des
>     fichiers, et notamment le jeu de caractères utilisé, le type de
>     structure, la longueur des enregistrements, les caractères
>     séparateur de zone et séparateur d'enregistrement.|
>     La creation d'un PDF incluant notamment la ligne 3°, à télécharger
>     depuis le wizard serait un début de solution.
>
Dans la version 8 d'Odoo, le module qui génère le FEC était un wizard en 
2 étapes, et l'étape finale affichait l'information concernant 
l'encodage des caractères (UTF-8). Je vois que, depuis que l'éditeur à 
récupéré la maintenance du module à partir d'Odoo 9, le wizard ne 
contient plus qu'une seule étape. Je pense que la solution serait 
d'afficher ces informations dans la fenêtre du wizard.
Vous pouvez faire une pull request pour améliorer ce point (ou demander 
à votre intégrateur de la faire) ; je soutiendrai cette amélioration.

>   * Les expert-comptables ont un nouveau logiciel de verification de
>     FEC sous la forme de macro VBA, qui a des problèmes de lecture si
>     il y a des tabulations dans les champs, il doit prendre en compte
>     les deux délimiteurs tab et pipe sur le même fichier. Dans le
>     script Odoo est-il possible de faire en sorte que les tabulations
>     soient supprimées.
>
Le fichier FEC généré par Odoo utilise "|" comme séparateur de champ, il 
n'y a donc a priori pas de raisons d'interpéter les tabulations comme 
séparateur de champs. Peut-être un bug à remonter dans la macro VBA...
Mais si vous tenez à le faire coté Odoo, vous pouvez modifier la requête 
SQL dans le code ; il y a déjà ce qu'il faut dedans pour retirer les "|" 
des libellés des écritures comptables pour être sûr qu'il n'y ait pas de 
séparateurs de champs "inattendus", vous pouvez vous en inspirer pour 
faire pareil pour les tabulations.

>   * Notre experts comptable ne peut pas importer le FEC dans son
>     logiciel d'analyse, car les comptes auxiliaires sont indiqués sur
>     tout les comptes, alors que d'après notre expert, il ne devrait
>     être que sur les 401, 411. D'après la loi il n'est explicitement
>     indiqué les comptes à exclure (ou à inclure) d'avoir un compte
>     auxiliaire. Afin de faciliter le travail de ces derniers, le
>     rajout d'un champs des comptes avec compte auxiliaires dans le
>     wizard serait-il possible ?
>
C'est vrai que Odoo renseigne le champ Partenaire sur toutes les lignes 
d'écritures dans les journaux d'achat et vente quand la pièce comptable 
est générée par la facture, et pas seulement sur les lignes 401 et 411 
comme on pourrait s'y attendre. Vu que le blocage concerne le logiciel 
de votre expert comptable et que cela ne ressort pas en erreur dans le 
logiciel de validation de l'administration fiscale 
http://www.economie.gouv.fr/dgfip/outil-test-des-fichiers-des-ecritures-comptables-fec 
, je pense que ce sera difficile de justifier une modification 
directement dans le module officiel ; je vous conseille de le faire via 
un petit développement spécifique.

>   * La date de lettrage indiqué dans Odoo est celle du jour où est
>     réalisé le lettrage. Or cette note
>     http://www.suiteexpert.fr/public/documents/awcompta/A47_AnnexeTechnique.pdf,
>     serait plutôt d'avis a indiquer la date du plus vieux mouvement.
>     Qu'en pensez-vous ?
>
Je suis très surpris de leur interprétation. Si on indique dans la 
colonne "Date de lettrage" la date du plus vieux mouvement, ce n'est pas 
très utile car on a déjà cette information dans le fichier FEC au niveau 
du champ Date de l'écriture...
Si on lit le BOFIP, ils disent : http://bofip.impots.gouv.fr/bofip/9028-PGP
<<

La date de lettrage de l’écriture correspond à la date à laquelle 
l’opération de lettrage a été validée dans le système comptable.

 >>

ce qui me semble plus logique (et correspond à l'implémentation actuelle).

-- 
Alexis de Lattre
